name: Yellow Gal High Definition
favicon: null
layout_spectrum: 0.7792412976268679
typography_spectrum: 0.744150975253433
title: Video Production Services
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.06985168089158833
  lightness: 0.410517422715202
  saturation: 0.46407843357883394
  rhythmicContrast: 0.21483549126423895
purpose: []
